services:
  mysql:
    image: mysql:8.0.39-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_DATABASE=insclone
    ports:
      - "3307:3306"
    networks:
      - insclone_network
    volumes:
      - mysql_data:/var/lib/mysql
  

  backend:
    build: ./ins-be
    ports:
      - "8888:8888"
    networks:
      - insclone_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/insclone
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  frontend:
    build: ./ins-fe
    networks:
      - insclone_network
    ports:
      - "4545:80"

networks:
  insclone_network:
    driver: bridge

volumes:
  mysql_data: 
    driver: local