server:
  port: 8888

spring:
  application:
    name: ins-be
  datasource:
    url: jdbc:mysql://mysql:3306/insclone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


jwt:
  signerKey: ZnjLwNmSRIuZ1PbtYkTEbUC60gEbjucoBYT20JY2HQjJtA8hf4poYAav6NAY7uxL


outbound:
  client-id: "1040903330486-pjq1nditab2guhaolurvguru7b592m5o.apps.googleusercontent.com"
  client-secret: "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"
  redirect-uri: "http://localhost:5173/authenticate"


